### ISSUE TITLE
대요정 버그

### ISSUE THREAD

**Issue by eradotio** [ammonia1815/EratohoRK#39]
[save05.zip](https://github.com/ammonia1815/EratohoRK/files/2635902/save05.zip)

대요정에게 페니스 밴드를 장착당한 상태에서 봉사중일 때 조교자 만족 이벤트로 인해 페니스 밴드가 제거되어도 여전히 삽입중으로 인식됩니다.

페니스 없이 V삽입 플래그가 켜져있어서 그런지 특정 이벤트를 무한 반복하는 현상이 일어나네요.
세이브 파일 첨부했습니다.

**Comment by ammonia1815** [comment]
아나타가 페니스밴드를 장착하고 대요정을 대만족시킨 후 유전자를 요구했을 시 더 이상 무한회화가 발생하지 않음
